insert into categorie values (9,'Sportive'),
	(13,'Roadster'),
	(6,'Routière & GT'),
	(10,'Trail'),
	(3,'Custom'),
	(19,'Sport-GT'),
	(14,'Super motard'),
	(4,'Enduro'),
	(30,'Hors categorie'),
	(26,'Superbike'),
	(2,'Cross'),
	(8,'Side car'),
	(32,'Supersport'),
	(27,'MotoGP');

insert into marque(id,logo,nom,pays,annee,status,grand) values(1, 'https://www.motoplanete.com/47-moto/47-moto-logo.gif', '47 Moto', 'Etats-Unis', '2017', 'En activité',false),
	(2, 'https://www.motoplanete.com/ABSAF/absaf-logo.jpg', 'ABSAF', 'Pays-Bas', '1981', 'En activité',false),
	(3, 'https://www.motoplanete.com/Acabion/acabion-logo.png', 'Acabion', 'Suisse', '1989', 'En activité',false),
	(4, 'https://www.motoplanete.com/accossato/accossato-logo.jpg', 'Accossato', 'Italie', '1973', 'En activité',false),
	(5, 'https://www.motoplanete.com/Adiva/adiva-logo.png', 'Adiva', 'Japon', '2006', 'En activité',false),
	(6, 'https://www.motoplanete.com/Adly/Adly-logo.png', 'Adly', 'Taïwan', '1978', 'En activité',false),
	(7, 'https://www.motoplanete.com/Aero-Motorcycles/Areo-motorcycle-logo-2.png', 'Aero Motorcycles', 'Italie', '2016', 'En activité',false),
	(8, 'https://www.motoplanete.com/AJP/AJP-logo.jpg', 'AJP', 'Portugal', '1987', 'En activité',false),
	(9, 'https://www.motoplanete.com/Amen/Amen-logo.jpg', 'Amen', 'Etats-Unis', '1999', 'En activité',false),
	(10, 'https://www.motoplanete.com/Apollo-chine/Apollo-china-logo.jpg', 'Apollo (CHI)', 'Chine', '2001', 'En activité',false),
	(11, 'https://www.motoplanete.com/aprilia/Aprilia.png', 'Aprilia', 'Italie', '1945', 'En activité',false),
	(12, 'https://www.motoplanete.com/AQG/AQG-logo.png', 'AQG', 'Italie', '0', 'En activité',false),
	(13, 'https://www.motoplanete.com/ARC-vehicle/ARC-vehicle-logo-mini.gif', 'ARC Vehicle', 'Angleterre', '2017', 'En activité',false),
	(14, 'https://www.motoplanete.com/Arch/Arch-logo.jpg', 'Arch Motorcycle', 'Etats-Unis', '2011', 'En activité',false),
	(15, 'https://www.motoplanete.com/Archive-Motorcycle/Archive-Motorcycle-logo.jpg', 'Archive Motorcycle', 'France', '2016', 'En activité',false),
	(16, 'https://www.motoplanete.com/Ariel/ariel-logo-vintage.png', 'Ariel', 'Angleterre', '1870', 'En activité',false),
	(17, 'https://www.motoplanete.com/Arlen-Ness/Arlen-Ness-logo-2.png', 'Arlen Ness', 'Etats-Unis', '1960', 'En activité',false),
	(18, 'https://www.motoplanete.com/armotia/Armotia-logo.gif', 'Armotia', 'Italie', '2013', 'En activité',false),
	(19, 'https://www.motoplanete.com/Asiawing/Asiawing-logo.png', 'Asiawing', 'Chine', '2007', 'En activité',false),
	(20, 'https://www.motoplanete.com/Askoll/Askoll-logo.gif', 'Askoll', 'Italie', '1978', 'En activité',false),
	(21, 'https://www.motoplanete.com/Aston-Martin/Aston-martin-logo-200-px.png', 'Aston Martin', 'Angleterre', '1913', 'En activité',false),
	(22, 'https://www.motoplanete.com/Asya-Motor/Asya-motor-logo.png', 'Asya Motor', 'Turquie', '0', 'En activité',false),
	(23, 'https://www.motoplanete.com/Atlas-Honda/Atlas-Honda-logo.png', 'Atlas Honda', 'Pakistan', '1962', 'En activité',false),
	(24, 'https://www.motoplanete.com/avinton/logo-avinton.jpg', 'Avinton', 'France', '2012', 'En activité',false),
	(25, 'https://www.motoplanete.com/baccio/baccio-logo.JPG', 'Baccio', 'Uruguay', '2008', 'En activité',false),
	(26, 'https://www.motoplanete.com/Bakker/bakker-logo.jpg', 'Bakker', 'Pays-Bas', '1973', 'En activité',false),
	(27, 'https://www.motoplanete.com/Bandit9/Bandit9-logo.jpg', 'Bandit9', 'Vietnam', '2011', 'En activité',false),
	(28, 'https://www.motoplanete.com/baodiao/baodiao-logo.jpg', 'Baodiao', 'Chine', '1998', 'En activité',false),
	(29, 'https://www.motoplanete.com/baotian/baotian-logo.jpg', 'Baotian', 'Chine', '1994', 'En activité',false),
	(30, 'https://www.motoplanete.com/bashan/bashan-logo.jpg', 'Bashan', 'Chine', '0', 'En activité',false),
	(31, 'https://www.motoplanete.com/bastos/bastos-logo.jpg', 'Bastos', 'France', '2006', 'En activité',false),
	(32, 'https://www.motoplanete.com/BBR/BBR-logo.JPG', 'BBR', 'Etats-Unis', '1977', 'En activité',false),
	(33, 'https://www.motoplanete.com/beale/beale-logo.JPG', 'Beale', 'Angleterre', '1990', 'En activité',false),
	(34, 'https://www.motoplanete.com/beare/beare-logo.JPG', 'Beare', 'Australie', '1991', 'En activité',false),
	(35, 'https://www.motoplanete.com/benda-motor/Benda-motor-logo.png', 'Benda Motor', 'Chine', '1994', 'En activité',false),
	(36, 'https://www.motoplanete.com/benelli/benelli_logo.gif', 'Benelli', 'Italie', '1911', 'En activité',false),
	(37, 'https://www.motoplanete.com/bidalot/Bidalot-logo.png', 'Bidalot', 'France', '1968', 'En activité',false),
	(38, 'https://www.motoplanete.com/big-bear-choppers/big-bear-choppers-logo.JPG', 'Big Bear Choppers', 'Etats-Unis', '1998', 'En activité',false),
	(39, 'https://www.motoplanete.com/bimota/bimota.gif', 'Bimota', 'Italie', '1972', 'En activité',false),
	(40, 'https://www.motoplanete.com/bisan/bisan-logo.jpg', 'Bisan', 'Turquie', '1963', 'En activité',false),
	(41, 'https://www.motoplanete.com/Black-douglas/black-douglas-logo.png', 'Black Douglas', 'Italie', '2012', 'En activité',false),
	(42, 'https://www.motoplanete.com/Blacksmith-Electric/Blacksmith-Electric-logo.jpg', 'Blacksmith Electric', 'Inde', '2003', 'En activité',false),
	(43, 'https://www.motoplanete.com/blaney/blaney-logo.bmp', 'Blaney', 'Irlande', '1996', 'En activité',false),
	(44, 'https://www.motoplanete.com/blata/blata-logo.JPG', 'Blata', 'République Tchèque', '1991', 'En activité',false),
	(45, 'https://www.motoplanete.com/bmw/BMW-logo-2020-mini-a.png', 'BMW', 'Allemagne', '1916', 'En activité',false),
	(46, 'https://www.motoplanete.com/Boss-Hoss/Boss-Hoss-logo.jpg', 'Boss Hoss', 'Etats-Unis', '1990', 'En activité',false),
	(47, 'https://www.motoplanete.com/Bourget/logo-Bourget-2.png', 'Bourget', 'Etats-Unis', '1993', 'En activité',false),
	(48, 'https://www.motoplanete.com/boxer-design/logo_boxer_design.jpg', 'Boxer', 'France', '1984', 'En activité',false),
	(49, 'https://www.motoplanete.com/Boyd-Motor-Company/Boyd-logo-3.jpg', 'Boyd Motor Company', 'Etats-Unis', '0', 'En activité',false),
	(50, 'https://www.motoplanete.com/Brasch/Brasch-Design-logo.jpg', 'Brasch', 'Suisse', '2010', 'En activité',false),
	(51, 'https://www.motoplanete.com/Britten/britten-logo.jpg', 'Britten', 'Nouvelle-Zélande', '1992', 'En activité',false),
	(52, 'https://www.motoplanete.com/Brixton/Brixton-logo.jpg', 'Brixton', 'Autriche', '2016', 'En activité',false),
	(53, 'https://www.motoplanete.com/brough-superior/brough-superior-logo.gif', 'Brough Superior', 'Angleterre', '1919', 'En activité',false),
	(54, 'https://www.motoplanete.com/BSE-Bosuer/logo-bse-bosuer.png', 'BSE Bosuer', 'Chine', '0', 'En activité',false),
	(55, 'https://www.motoplanete.com/Bucci/Bucci-moto-logo.jpg', 'Bucci', 'Italie', '0', 'En activité',false),
	(56, 'https://www.motoplanete.com/Bulldog-Motors-all/Bulldog-motors-logo.png', 'Bulldog Motors', 'Allemagne', '2019', 'En activité',false),
	(57, 'https://www.motoplanete.com/Bullit/Bullit-logo.jpg', 'Bullit Motorcycles', 'Belgique', '2013', 'En activité',false),
	(58, 'https://www.motoplanete.com/Bye-Bike/bye-bike-logo.jpeg', 'Bye Bike', 'Espagne', '2013', 'En activité',false),
	(59, 'https://www.motoplanete.com/Can-Am/CanAm-Logo.jpg', 'Can-Am', 'Canada', '1973', 'En activité',false),
	(60, 'https://www.motoplanete.com/ccm/ccm-logo.gif', 'CCM (UK)', 'Angleterre', '1971', 'En activité',false),
	(61, 'https://www.motoplanete.com/CF-Moto/CF-moto-logo.jpg', 'CF MOTO', 'Chine', '1989', 'En activité',false),
	(62, 'https://www.motoplanete.com/CH-racing/CH-racing-logo.jpg', 'CH Racing', 'Italie', '1993', 'En activité',false),
	(63, 'https://www.motoplanete.com/Chang-Jiang-Xiang-Jiang/ChangJiang-logo-2.jpg', 'Chang Jiang / Xiang Jiang', 'Chine', '1961', 'En activité',false),
	(64, 'https://www.motoplanete.com/Cheney/cheney-logo.gif', 'Cheney', 'Angleterre', '1964', 'En activité',false),
	(65, 'https://www.motoplanete.com/Chesini/Chesini-logo.jpg', 'Chesini', 'Italie', '1925', 'En activité',false),
	(66, 'https://www.motoplanete.com/Clipic/Clipic-logo.gif', 'Clipic', 'Espagne', '1995', 'En activité',false),
	(67, 'https://www.motoplanete.com/Cobra/Cobra-logo.jpg', 'Cobra', 'Etats-Unis', '1993', 'En activité',false),
	(68, 'https://www.motoplanete.com/Colove-motorcycles/colove-logo.png', 'Colove', 'Tibet', '1995', 'En activité',false),
	(69, 'https://www.motoplanete.com/Corven/Corven-logo.jpg', 'Corven', 'Argentine', '2008', 'En activité',false),
	(70, 'https://www.motoplanete.com/Covingtons/Covingtons-logo.jpg', 'Covingtons', 'Etats-Unis', '1993', 'En activité',false),
	(71, 'https://www.motoplanete.com/CPI/CPI-logo.jpg', 'CPI', 'Taïwan', '1991', 'En activité',false),
	(72, 'https://www.motoplanete.com/CPO/CPO-logo.jpg', 'CPO', 'Allemagne', '1980', 'En activité',false),
	(73, 'https://www.motoplanete.com/Crighton-Racing/crighton-racing-logo.png', 'Crighton Racing', 'Angleterre', '2013', 'En activité',false),
	(74, 'https://www.motoplanete.com/Crown-Lifan/Crown-Lifan-logo.jpeg', 'Crown Lifan', 'Pakistan', '2002', 'En activité',false),
	(75, 'https://www.motoplanete.com/CRZ/CRZ-logo.png', 'CRZ', 'France', '2006', 'En activité',false),
	(76, 'https://www.motoplanete.com/California-Scooter-Company/CSC-logo.jpg', 'CSC - California Scooter Company', 'Etats-Unis', '1989', 'En activité',false),
	(77, 'https://www.motoplanete.com/Current-Motor/Current-Motor-logo.jpg', 'Current Motor', 'Etats-Unis', '2008', 'En activité',false),
	(78, 'https://www.motoplanete.com/Curtiss-Motorcycles/Curtiss-logo.gif', 'Curtiss Motorcycles', 'Etats-Unis', '2018', 'En activité',false),
	(79, 'https://www.motoplanete.com/Custom-Chrome/Custom-Chrome-logo-inc.jpg', 'Custom Chrome', 'Etats-Unis', '1970', 'En activité',false),
	(80, 'https://www.motoplanete.com/Cyclone-chine/cyclone-zongshen-logo.JPG', 'Cyclone (CHI)', 'Chine', '0', 'En activité',false),
	(81, 'https://www.motoplanete.com/Cyril-Huze/cyril-huze-logo.jpg', 'Cyril Huze', 'Etats-Unis', '0', 'En activité',false),
	(82, 'https://www.motoplanete.com/cz-cezeta/cz-cezeta-logo.jpg', 'CZ - Cezeta', 'Tchécoslovaquie', '1932', 'En activité',false),
	(83, 'https://www.motoplanete.com/daelim/daelim-logo.gif', 'Daelim', 'Corée', '1962', 'En activité',false),
	(84, 'https://www.motoplanete.com/Dafra/Dafra-logo.jpg', 'Dafra', 'Brésil', '2008', 'En activité',false),
	(85, 'https://www.motoplanete.com/DAM/DAM-logo.png', 'DAM', 'Etats-Unis', '2002', 'En activité',false),
	(86, 'https://www.motoplanete.com/Damon-motorcycles/Damon-logo-mini.jpg', 'Damon', 'Canada', '2017', 'En activité',false),
	(87, 'https://www.motoplanete.com/dayang/dayang-logo.jpg', 'Dayang', 'Chine', '1983', 'En activité',false),
	(88, 'https://www.motoplanete.com/Dayun/Dayun-logo.jpg', 'Dayun', 'Chine', '1999', 'En activité',false),
	(89, 'https://www.motoplanete.com/Deller/Deller-logo.jpg', 'Deller', 'Russie', '2012', 'En activité',false),
	(90, 'https://www.motoplanete.com/Demak/Demak-Logo-2.png', 'Demak', 'Malaisie', '0', 'En activité',false),
	(91, 'https://www.motoplanete.com/derbi/logo.gif', 'Derbi', 'Espagne', '1923', 'En activité',false),
	(92, 'https://www.motoplanete.com/Devot-Motors/devot-motors-logo.gif', 'Devot', 'Inde', '2019', 'En activité',false),
	(93, 'https://www.motoplanete.com/DHZ/DHZ-logo.png', 'DHZ', 'Australie', '2004', 'En activité',false),
	(94, 'https://www.motoplanete.com/di-blasi/DiBlasi_Logo.jpg', 'Di Blasi', 'Italie', '1992', 'En activité',false),
	(95, 'https://www.motoplanete.com/Dihao/Diaho-logo.gif', 'Dihao', 'Chine', '1998', 'En activité',false),
	(96, 'https://www.motoplanete.com/Direct-Bikes/Direct-Bikes-logo.png', 'Direct Bikes', 'Angleterre', '2008', 'En activité',false),
	(97, 'https://www.motoplanete.com/Dirico/Dirico-logo.png', 'Dirico', 'Etats-Unis', '2009', 'En activité',false),
	(98, 'https://www.motoplanete.com/dnepr-dniepr/Dnepr-logo-dniepr.jpg', 'Dniepr - Dnepr', 'Ukraine', '1967', 'En activité',false),
	(99, 'https://www.motoplanete.com/dodge/dodge-logo.gif', 'Dodge', 'Etats-Unis', '1914', 'En activité',false),
	(100, 'https://www.motoplanete.com/Doohan/doohan-logo-2.png', 'Doohan', 'Chine', '2014', 'En activité',false),
	(101, 'https://www.motoplanete.com/Druid-Motorcycle-Company/Druid-Motorcycle-Company-logo-mini.gif', 'Druid Motorcycle Company', 'Etats-Unis', '2016', 'En activité',false),
	(102, 'https://www.motoplanete.com/drysdale/drysdale-logo.JPG', 'Drysdale', 'Australie', '1994', 'En activité',false),
	(103, 'https://www.motoplanete.com/ducati/Ducati.png', 'Ducati', 'Italie', '1926', 'En activité',false),
	(104, 'https://www.motoplanete.com/E-Rider/E-rider-logo.png', 'E Rider', 'Angleterre', '0', 'En activité',false),
	(105, 'https://www.motoplanete.com/E-Choppers/e-choppers-logo.png', 'E-Choppers', 'Suisse', '2016', 'En activité',false),
	(106, 'https://www.motoplanete.com/E-max/E-max-logo-mini.jpg', 'E-max', 'Allemagne', '2003', 'En activité',false),
	(107, 'https://www.motoplanete.com/ecomobile/ecomobile-peraves-logo.jpg', 'Ecomobile', 'Suisse', '1982', 'En activité',false),
	(108, 'https://www.motoplanete.com/ecosse-moto/Ecosse-moto-logo.jpg', 'Ecosse', 'Etats-Unis', '2001', 'En activité',false),
	(109, 'https://www.motoplanete.com/egli/egli-logo.jpg', 'Egli', 'Suisse', '1968', 'En activité',false),
	(110, 'https://www.motoplanete.com/Electric-motion/electric-motion-logo-2.png', 'Electric Motion', 'France', '2009', 'En activité',false),
	(111, 'https://www.motoplanete.com/ElMoto/Elmoto_logo.png', 'ElMoto', 'Allemagne', '2009', 'En activité',false),
	(112, 'https://www.motoplanete.com/Emco/EMCO-logo.jpg', 'Emco', 'Allemagne', '2011', 'En activité',false),
	(113, 'https://www.motoplanete.com/Emflux/Emflux-logo-small.gif', 'Emflux', 'Inde', '2016', 'En activité',false),
	(114, 'https://www.motoplanete.com/Energica/Energica-logo.jpg', 'Energica', 'Italie', '2014', 'En activité',false),
	(115, 'https://www.motoplanete.com/erockit/erockit-logo.jpg', 'eRockit', 'Allemagne', '2008', 'En activité',false),
	(116, 'https://www.motoplanete.com/Essence-motocycles/essence-motocycles-logo-100px.png', 'Essence Motocycles', 'France', '2015', 'En activité',false),
	(117, 'https://www.motoplanete.com/Etrix/Etrix-logo-big.gif', 'Etrix', 'Suisse', '2011', 'En activité',false),
	(118, 'https://www.motoplanete.com/ETT/ETT-logo.gif', 'ETT Industries', 'France', '2013', 'En activité',false),
	(119, 'https://www.motoplanete.com/Eurocka/Eurocka-logo.jpg', 'Eurocka', 'France', '2005', 'En activité',false),
	(120, 'https://www.motoplanete.com/Evoke/Evoke-logo.png', 'Evoke', 'Chine', '2013', 'En activité',false),
	(121, 'https://www.motoplanete.com/EVT/EVT-logo.jpg', 'EVT', 'Chine', '1999', 'En activité',false),
	(122, 'https://www.motoplanete.com//excelsior-henderson-logo.jpg', 'Excelsior-Henderson', 'Etats-Unis', '1998', 'En activité',false),
	(123, 'https://www.motoplanete.com/Falcon/Falcon_motorcycles_logo.jpg', 'Falcon', 'Etats-Unis', '2008', 'En activité',false),
	(124, 'https://www.motoplanete.com/Fantic/Fantic-logo.png', 'Fantic', 'Italie', '1968', 'En activité',false),
	(125, 'https://www.motoplanete.com/Fast%20By%20Ferracci/Fast-by-ferracci-logo.png', 'Fast By Ferracci', 'Italie', '1980', 'En activité',false),
	(126, 'https://www.motoplanete.com/Faucon-moto/Faucon-moto-logo.jpg', 'Faucon Moto', 'France', '2017', 'En activité',false),
	(127, 'https://www.motoplanete.com/mondial/mondial.gif', 'FB Mondial', 'Italie', '1929', 'En activité',false),
	(128, 'https://www.motoplanete.com/feuling/Feuling_logo-fiche.png', 'Feuling', 'Etats-Unis', '1999', 'En activité',false),
	(129, 'https://www.motoplanete.com/FGR/FGR-logo-mini.jpg', 'FGR', 'République Tchèque', '1992', 'En activité',false),
	(130, 'https://www.motoplanete.com/FKMotors/FKMotors-logo.jpg', 'FKM', 'Chine', '2014', 'En activité',false),
	(131, 'https://www.motoplanete.com/fly-free-motorcycles/Fly-Free-logo-2.jpg', 'Fly Free', 'Etats-Unis', '2016', 'En activité',false),
	(132, 'https://www.motoplanete.com/Flyrite-Choppers/Flyrite-Choppers-logo.jpg', 'Flyrite Choppers', 'Etats-Unis', '2002', 'En activité',false),
	(133, 'https://www.motoplanete.com/Frisco-Motorcycles/Frisco-motorcycles-logo.JPG', 'Frisco Motorcycles', 'France', '1990', 'En activité',false),
	(134, 'https://www.motoplanete.com/Fuell/Fuell-logo.png', 'Fuell', 'Etats-Unis', '2019', 'En activité',false),
	(135, 'https://www.motoplanete.com/FX-Bikes/FX-Bikes-logo.png', 'FX Bikes', 'Nouvelle-Zélande', '2011', 'En activité',false),
	(136, 'https://www.motoplanete.com/Garelli/Garelli-logo.jpg', 'Garelli', 'Italie', '1913', 'En activité',false),
	(137, 'https://www.motoplanete.com/gas-gas/Gas-Gas-Logo-HD.png', 'Gas Gas', 'Espagne', '1982', 'En activité',false),
	(138, 'https://www.motoplanete.com/Geely/Geely-logo.png', 'Geely', 'Chine', '1986', 'En activité',false),
	(139, 'https://www.motoplanete.com/Genata/Genata-logo.png', 'Genata', 'Chine', '2003', 'En activité',false),
	(140, 'https://www.motoplanete.com/Genuine-Scooter/Genuine-scooter-logo.jpg', 'Genuine Scooter', 'Etats-Unis', '2002', 'En activité',false),
	(141, 'https://www.motoplanete.com/GG/GG-logo.jpg', 'GG', 'Suisse', '1983', 'En activité',false),
	(142, 'https://www.motoplanete.com/Ghani/Ghani-logo.jpg', 'Ghani', 'Pakistan', '2004', 'En activité',false),
	(143, 'https://www.motoplanete.com/Ghezzi-Brian/Ghezzi-Brian-logo.png', 'Ghezzi & Brian', 'Italie', '1995', 'En activité',false),
	(144, 'https://www.motoplanete.com/Gibbs/Gibbs-logo.jpg', 'Gibbs', 'Etats-Unis', '1997', 'En activité',false),
	(145, 'https://www.motoplanete.com/gilera/gilera-logo.jpg', 'Gilera', 'Italie', '1909', 'En activité',false),
	(146, 'https://www.motoplanete.com/Gladstone/Gladstone-logo-high.png', 'Gladstone', 'Angleterre', '1984', 'En activité',false),
	(147, 'https://www.motoplanete.com/godden/Godden-logo.gif', 'Godden', 'Angleterre', '1978', 'En activité',false),
	(148, 'https://www.motoplanete.com/Godet/Godet-logo.png', 'Godet', 'France', '2000', 'En activité',false),
	(149, 'https://www.motoplanete.com/Govecs/Govecs-logo.png', 'Govecs', 'Allemagne', '2013', 'En activité',false),
	(150, 'https://www.motoplanete.com/GPX/GPX-logo.jpg', 'GPX', 'Thailande', '2007', 'En activité',false),
	(151, 'https://www.motoplanete.com/GRC-Moto/GRC_Moto-logo.png', 'GRC Moto', 'Italie', '2001', 'En activité',false),
	(152, 'https://www.motoplanete.com//logo-gunshot.png', 'Gunshot', 'France', '2004', 'En activité',false),
	(153, 'https://www.motoplanete.com/Gypsy/gypsy-logo.jpg', 'Gypsy', 'Canada', '2002', 'En activité',false),
	(154, 'https://www.motoplanete.com/Hangpai/Hangpai-logo.png', 'Hangpai', 'Chine', '2006', 'En activité',false),
	(155, 'https://www.motoplanete.com/Hanway/Hanway-logo.png', 'Hanway', 'Chine', '2000', 'En activité',false),
	(156, 'https://www.motoplanete.com/Haojin/Haojin-logo.png', 'Haojin', 'Chine', '0', 'En activité',false),
	(157, 'https://www.motoplanete.com/Haojue/Haojue-logo.png', 'Haojue', 'Chine', '1992', 'En activité',false),
	(158, 'https://www.motoplanete.com/harley-davidson/Logo-Harley-Davidson-cycles.png', 'Harley-Davidson', 'Etats-Unis', '1903', 'En activité',false),
	(159, 'https://www.motoplanete.com/Hartford/Hartford-logo.jpg', 'Hartford', 'Taïwan', '1995', 'En activité',false),
	(160, 'https://www.motoplanete.com/Havoc-Motorcycles/Havoc.jpg', 'Havoc Motorcycles', 'Canada', '2015', 'En activité',false),
	(161, 'https://www.motoplanete.com/Hazan-Motorworks/Hazan%20Motorworks.jpg', 'Hazan Motorworks', 'Etats-Unis', '2012', 'En activité',false),
	(162, 'https://www.motoplanete.com/Headbanger/Headbanger-logo.jpg', 'Headbanger', 'Italie', '2010', 'En activité',false),
	(163, 'https://www.motoplanete.com/Herald/Herald-logo.gif', 'Herald', 'Angleterre', '2009', 'En activité',false),
	(164, 'https://www.motoplanete.com/Herminelec/Herminelec-logo.gif', 'Herminelec', 'France', '2010', 'En activité',false),
	(165, 'https://www.motoplanete.com/Hero/Hero-logo.png', 'Hero', 'Inde', '1984', 'En activité',false),
	(166, 'https://www.motoplanete.com/Hero-Electric/Hero-Electric-logo.jpeg', 'Hero Electric', 'Inde', '2007', 'En activité',false),
	(167, 'https://www.motoplanete.com/Hesketh/Hesketh_Logo-mini.jpg', 'Hesketh', 'Angleterre', '1982', 'En activité',false),
	(168, 'https://www.motoplanete.com/HM-Moto/HM-Moto-logo.jpg', 'HM Moto', 'Italie', '1988', 'En activité',false),
	(169, 'https://www.motoplanete.com/honda/Honda.png', 'Honda', 'Japon', '1948', 'En activité',false),
	(170, 'https://www.motoplanete.com/Honley/Honley-UK-logo.jpg', 'Honley', 'Angleterre', '2012', 'En activité',false),
	(171, 'https://www.motoplanete.com/horex/horex-logo.gif', 'Horex', 'Allemagne', '1923', 'En activité',false),
	(172, 'https://www.motoplanete.com/Horwin/horwin-logo.png', 'Horwin', 'Autriche', '2017', 'En activité',false),
	(173, 'https://www.motoplanete.com/Huasha/Huasha-logo.jpg', 'Huasha', 'Chine', '1999', 'En activité',false),
	(174, 'https://www.motoplanete.com/husqvarna/husqvarna.jpg', 'Husqvarna', 'Suède', '1903', 'En activité',false),
	(175, 'https://www.motoplanete.com/Ice-Bear/Ice-bear-logo.png', 'Ice Bear', 'Etats-Unis', '2006', 'En activité',false),
	(176, 'https://www.motoplanete.com/indian/Indian.png', 'Indian', 'Etats-Unis', '1901', 'En activité',false),
	(177, 'https://www.motoplanete.com/Innoscooter/InnoScooter-Logo.jpg', 'InnoScooter', 'Allemagne', '2007', 'En activité',false),
	(178, 'https://www.motoplanete.com/Irving-Vincent/Irving_Vincent-logo.jpg', 'Irving Vincent', 'Australie', '1977', 'En activité',false),
	(179, 'https://www.motoplanete.com/Italjet/index.jpg', 'Italjet', 'Italie', '1959', 'En activité',false),
	(180, 'https://www.motoplanete.com/Italmoto/Italmoto-logo.png', 'Italmoto', 'Italie', '1952', 'En activité',false),
	(181, 'https://www.motoplanete.com/Izuka/Izuka-logo.gif', 'Izuka', 'Mexique', '2004', 'En activité',false),
	(182, 'https://www.motoplanete.com/James-B/James-b-logo.jpg', 'James B.', 'France', '2008', 'En activité',false),
	(183, 'https://www.motoplanete.com/Janus/Janus-Logo-2.png', 'Janus', 'Etats-Unis', '2011', 'En activité',false),
	(184, 'https://www.motoplanete.com/Jawa/Jawa-logo-mini.jpg', 'Jawa', 'Tchécoslovaquie', '1929', 'En activité',false),
	(185, 'https://www.motoplanete.com/JetPack-Aviation/Jetpack-Aviation-Logo-square1.png', 'JetPack Aviation', 'Etats-Unis', '2016', 'En activité',false),
	(186, 'https://www.motoplanete.com/Jiajue/Jiajue-logo.jpg', 'Jiajue', 'Chine', '1990', 'En activité',false),
	(187, 'https://www.motoplanete.com/Jialing/Jialing-logo.jpg', 'Jialing', 'Chine', '1979', 'En activité',false),
	(188, 'https://www.motoplanete.com/Jianshe/Jianshe-logo.jpg', 'Jianshe', 'Chine', '1980', 'En activité',false),
	(189, 'https://www.motoplanete.com/Jianuo/Jianuo-logo.jpg', 'Jianuo', 'Chine', '2006', 'En activité',false),
	(190, 'https://www.motoplanete.com/Jiapeng/Jiapeng-logo.jpg', 'Jiapeng', 'Chine', '1998', 'En activité',false),
	(191, 'https://www.motoplanete.com/Jincheng/Jincheng.gif', 'Jincheng', 'Chine', '1992', 'En activité',false),
	(192, 'https://www.motoplanete.com/Jinlun/Jinlun-logo.jpg', 'Jinlun', 'Chine', '1993', 'En activité',false),
	(193, 'https://www.motoplanete.com/Jinyi/Jinyi-motor-logo.jpg', 'Jinyi Motor', 'Chine', '0', 'En activité',false),
	(194, 'https://www.motoplanete.com/JM-Motors/JM-Motors-logo.png', 'JM Motors', 'France', '2002', 'En activité',false),
	(195, 'https://www.motoplanete.com/Jmstar/JMSTAR-logo.jpg', 'Jmstar', 'Chine', '2000', 'En activité',false),
	(196, 'https://www.motoplanete.com/Johammer/Johammer-logo.png', 'Johammer', 'Autriche', '2014', 'En activité',false),
	(197, 'https://www.motoplanete.com/Johnny-Pag/Johnny-Pag-logo.png', 'Johnny Pag', 'Etats-Unis', '2009', 'En activité',false),
	(198, 'https://www.motoplanete.com/Jonway/Jonway-logo.jpg', 'Jonway', 'Chine', '1990', 'En activité',false),
	(199, 'https://www.motoplanete.com/Jotagas/Jotagas-logo.png', 'Jotagas', 'Espagne', '2010', 'En activité',false),
	(200, 'https://www.motoplanete.com/JRL/JRL-logo-mini.jpg', 'JRL', 'Etats-Unis', '2005', 'En activité',false),
	(201, 'https://www.motoplanete.com/Kabirdass/Kabirdass-logo.jpg', 'Kabirdass', 'Inde', '2006', 'En activité',false),
	(202, 'https://www.motoplanete.com/Kalachnikov/Kalachnikov-logo.jpg', 'Kalachnikov', 'Russie', '2017', 'En activité',false),
	(203, 'https://www.motoplanete.com/Kanuni/Kanuni-logo.jpg', 'Kanuni', 'Turquie', '1987', 'En activité',false),
	(204, 'https://www.motoplanete.com/kawasaki/Kawasaki.png', 'Kawasaki', 'Japon', '1896', 'En activité',false),
	(205, 'https://www.motoplanete.com/Keeway/Keeway-logo.jpg', 'Keeway', 'Chine', '1999', 'En activité',false),
	(206, 'https://www.motoplanete.com/Kentoya/Kentoya-logo.gif', 'Kentoya', 'République Tchèque', '1994', 'En activité',false),
	(207, 'https://www.motoplanete.com/Kerox/logo-kerox.jpg', 'Kerox', 'France', '2009', 'En activité',false),
	(208, 'https://www.motoplanete.com/Kikker%205150/kikker-5150-logo.gif', 'Kikker 5150', 'Etats-Unis', '2006', 'En activité',false),
	(209, 'https://www.motoplanete.com/Kinetic/Kinetic-logo.jpg', 'Kinetic', 'Inde', '1972', 'En activité',false),
	(210, 'https://www.motoplanete.com/KMZ/KMZ-logo.png', 'KMZ', 'Ukraine', '1941', 'En activité',false),
	(211, 'https://www.motoplanete.com/Korado/Korado-logo.jpg', 'Korado', 'République Tchèque', '1994', 'En activité',false),
	(212, 'https://www.motoplanete.com/KRC-motors/krc-motors-logo.jpg', 'KRC Motors', 'Italie', '0', 'En activité',false),
	(213, 'https://www.motoplanete.com/Kreidler/Kreidler.jpg', 'Kreidler', 'Allemagne', '1950', 'En activité',false),
	(214, 'https://www.motoplanete.com/Kramer-motorcycles-markus/kraemer-motorcycle-logo.jpg', 'Krämer', 'Allemagne', '2014', 'En activité',false),
	(215, 'https://www.motoplanete.com/KSR-moto/ksr-moto-logo.gif', 'KSR Moto', 'Autriche', '2012', 'En activité',false),
	(216, 'https://www.motoplanete.com/ktm/KTM.png', 'KTM', 'Autriche', '1934', 'En activité',false),
	(217, 'https://www.motoplanete.com/Kuba%20Motor/Kuba-motor-logo.png', 'Kuba Motor', 'Turquie', '2004', 'En activité',false),
	(218, 'https://www.motoplanete.com/Kuberg/Kuberg-logo.jpg', 'Kuberg', 'République Tchèque', '2011', 'En activité',false),
	(219, 'https://www.motoplanete.com/Kumpan/Kumpan-logo.jpg', 'Kumpan', 'Allemagne', '2009', 'En activité',false),
	(220, 'https://www.motoplanete.com/Kuralkan/Kuralkan-logo.jpg', 'Kuralkan', 'Turquie', '1987', 'En activité',false),
	(221, 'https://www.motoplanete.com/KXD-Moto/KXD-Moto-logo.png', 'KXD Moto', 'Chine', '2002', 'En activité',false),
	(222, 'https://www.motoplanete.com/kymco/kymco-logo.gif', 'Kymco', 'Taïwan', '1963', 'En activité',false),
	(223, 'https://www.motoplanete.com/Kyota/Kyota-logo.jpg', 'Kyota', 'Chine', '0', 'En activité',false),
	(224, 'https://www.motoplanete.com/Lauge-Jensen/Lauge-Jensen-logo.png', 'Lauge Jensen', 'Danemark', '2009', 'En activité',false),
	(225, 'https://www.motoplanete.com/Lazareth/Lazareth-logo.png', 'Lazareth', 'France', '1998', 'En activité',false),
	(226, 'https://www.motoplanete.com/Lectrix/Lectrix-logo.jpg', 'Lectrix', 'Inde', '2007', 'En activité',false),
	(227, 'https://www.motoplanete.com/Leike/Leike-logo.jpg', 'Leike', 'Chine', '1996', 'En activité',false),
	(228, 'https://www.motoplanete.com/LEM/LEM-logo.jpg', 'Lem', 'Italie', '1974', 'En activité',false),
	(229, 'https://www.motoplanete.com/Leonhardt/Leonhardt-manufacturing-logo.gif', 'Leonhardt', 'Allemagne', '1970', 'En activité',false),
	(230, 'https://www.motoplanete.com/Leri/Leri-logo.jpg', 'Leri', 'Italie', '1898', 'En activité',false),
	(231, 'https://www.motoplanete.com/Levis/Levis-logo-small.jpg', 'Levis', 'Angleterre', '1911', 'En activité',false),
	(232, 'https://www.motoplanete.com/Lexmoto/Lexmoto-logo.png', 'Lexmoto', 'Angleterre', '2007', 'En activité',false),
	(233, 'https://www.motoplanete.com/Lifan/Lifan-logo.png', 'Lifan', 'Chine', '1992', 'En activité',false),
	(234, 'https://www.motoplanete.com/Lightning/lightning-motors-logo-2.png', 'Lightning', 'Etats-Unis', '2006', 'En activité',false),
	(235, 'https://www.motoplanete.com/Lingben/Lingben-logo.jpg', 'Lingben', 'Chine', '2001', 'En activité',false),
	(236, 'https://www.motoplanete.com/Lingken/Lingken-logo.jpg', 'Lingken', 'Chine', '1998', 'En activité',false),
	(237, 'https://www.motoplanete.com/Lit-Motors/Lit-Motors-logo-mini.jpg', 'Lit Motors', 'Etats-Unis', '2010', 'En activité',false),
	(238, 'https://www.motoplanete.com/LML/LML-logo.jpg', 'LML', 'Inde', '1984', 'En activité',false),
	(239, 'https://www.motoplanete.com/LMX-Bikes/LMX-bikes-logo-2.jpg', 'LMX Bikes', 'France', '2013', 'En activité',false),
	(240, 'https://www.motoplanete.com/Loncin/Loncin-logo.jpg', 'Loncin', 'Chine', '1993', 'En activité',false),
	(241, 'https://www.motoplanete.com/Longjia/Longjia-logo.png', 'Longjia', 'Chine', '1992', 'En activité',false),
	(242, 'https://www.motoplanete.com/Luxxon/Luxxon-logo.jpg', 'Luxxon', 'Allemagne', '0', 'En activité',false),
	(243, 'https://www.motoplanete.com/Lvneng/Lvneng-logo.gif', 'Lvneng', 'Chine', '1999', 'En activité',false),
	(244, 'https://www.motoplanete.com/Mac-Motorcycles/Mac-Motorcycles-logo.jpg', 'Mac Motorcycles', 'Angleterre', '2009', 'En activité',false),
	(245, 'https://www.motoplanete.com/MACBOR/Macbor-logo.png', 'Macbor', 'Espagne', '1999', 'En activité',false),
	(246, 'https://www.motoplanete.com/Magni/Magni-logo.gif', 'Magni (Italie - Samarate)', 'Italie', '1977', 'En activité',false),
	(247, 'https://www.motoplanete.com/Mahindra/Mahindra_Rise_New_Logo.svg.png', 'Mahindra', 'Inde', '1945', 'En activité',false),
	(248, 'https://www.motoplanete.com/Malaguti/Malaguti-logo.png', 'Malaguti', 'Italie', '1958', 'En activité',false),
	(249, 'https://www.motoplanete.com/Malcor/Malcor-logo.jpg', 'Malcor', 'Espagne', '2008', 'En activité',false),
	(250, 'https://www.motoplanete.com/Mankame/Mankame-logo.gif', 'Mankame', 'Inde', '2018', 'En activité',false),
	(251, 'https://www.motoplanete.com/mtt/MTT-logo.gif', 'Marine Turbine Technologies', 'Etats-Unis', '1990', 'En activité',false),
	(252, 'https://www.motoplanete.com/mash/logo-mash.jpg', 'Mash', 'France', '2012', 'En activité',false),
	(253, 'https://www.motoplanete.com/Matchless/Matchless-logo.gif', 'Matchless', 'Angleterre', '1901', 'En activité',false),
	(254, 'https://www.motoplanete.com/Mecatwin/mecatwin-logo.png', 'Mecatwin', 'France', '1997', 'En activité',false),
	(255, 'https://www.motoplanete.com/medusa-france/Medusa-france-logo.png', 'Medusa (FR)', 'France', '2016', 'En activité',false),
	(256, 'https://www.motoplanete.com/Mega-Machines/mega-machines-logo.jpg', 'Mega Machines', 'Allemagne', '1994', 'En activité',false),
	(257, 'https://www.motoplanete.com/Megelli/Megelli-logo.jpg', 'Megelli', 'Angleterre', '2004', 'En activité',false),
	(258, 'https://www.motoplanete.com/Meiduo/meiduo-logo.jpg', 'Meiduo', 'Chine', '1996', 'En activité',false),
	(259, 'https://www.motoplanete.com/Meijs/Meijs-logo.jpeg', 'Meijs', 'Pays-Bas', '2013', 'En activité',false),
	(260, 'https://www.motoplanete.com/Metiss-france/metiss-fr-logo.png', 'Metiss', 'France', '2004', 'En activité',false),
	(261, 'https://www.motoplanete.com/MicroMobility/micro-mobility.gif', 'Micro Mobility', 'Suisse', '1996', 'En activité',false),
	(262, 'https://www.motoplanete.com/midual/midual-logo-100px.png', 'Midual', 'France', '1992', 'En activité',false),
	(263, 'https://www.motoplanete.com/Mikilon/Mikilon-logo.jpg', 'Mikilon', 'Chine', '2006', 'En activité',false),
	(264, 'https://www.motoplanete.com/Minsk/Minsk-logo.png', 'Minsk', 'Biélorussie', '1951', 'En activité',false),
	(265, 'https://www.motoplanete.com/Mitt-motocycles/Mitt-motorycles-logo-2.png', 'Mitt', 'Espagne', '1980', 'En activité',false),
	(266, 'https://www.motoplanete.com/Mobilec/mobilec-logo.jpg', 'Mobilec', 'Suisse', '2008', 'En activité',false),
	(267, 'https://www.motoplanete.com/Modenas/MODENAS-Logo.jpg', 'Modenas', 'Malaisie', '1995', 'En activité',false),
	(268, 'https://www.motoplanete.com/Mondial-SA-argentine/Mondial-argentine-logo.jpg', 'Mondial S.A.', 'Argentine', '1972', 'En activité',false),
	(269, 'https://www.motoplanete.com/MondialMoto/MondialMoto-logo-resize.jpg', 'MondialMoto', 'Italie', '2007', 'En activité',false),
	(270, 'https://www.motoplanete.com/Montesa/Montesa-logo.jpg', 'Montesa', 'Espagne', '1944', 'En activité',false),
	(271, 'https://www.motoplanete.com/morini/logo-morini.gif', 'Morini', 'Italie', '1937', 'En activité',false),
	(272, 'https://www.motoplanete.com/Moriwaki/moriwaki_logo.png', 'Moriwaki', 'Japon', '1973', 'En activité',false),
	(273, 'https://www.motoplanete.com/moto-corsa-uk/Moto-Corsa-logo.jpg', 'Moto Corsa', 'Angleterre', '2018', 'En activité',false),
	(274, 'https://www.motoplanete.com/moto-guzzi/Moto_Guzzi.png', 'Moto-Guzzi', 'Italie', '1921', 'En activité',false),
	(275, 'https://www.motoplanete.com/Motoped/Motoped-logo.jpg', 'Motoped', 'Etats-Unis', '2013', 'En activité',false),
	(276, 'https://www.motoplanete.com/Motorhell/motorhell_logo.jpg', 'Motorhell', 'France', '2018', 'En activité',false),
	(277, 'https://www.motoplanete.com/Motorhispania/Motorhispania-MH-Motorcycles-logo.jpg', 'Motorhispania', 'Espagne', '1948', 'En activité',false),
	(278, 'https://www.motoplanete.com/Motorino/motorino_logo.jpg', 'Motorino', 'Canada', '2003', 'En activité',false),
	(279, 'https://www.motoplanete.com/MotoVert/MotoVert-logo.jpg', 'MotoVert', 'Australie', '2004', 'En activité',false),
	(280, 'https://www.motoplanete.com/Motowell/motowell-logo.jpg', 'Motowell', 'Hongrie', '2005', 'En activité',false),
	(281, 'https://www.motoplanete.com/Motrac/Motrac-logo.jpg', 'Motrac', 'Chine', '0', 'En activité',false),
	(282, 'https://www.motoplanete.com/Mutt-motorcycles/Mutt-motorcycles.gif', 'Mutt', 'Angleterre', '2014', 'En activité',false),
	(283, 'https://www.motoplanete.com/mv-agusta/MV_Agusta.png', 'MV-Agusta', 'Italie', '1945', 'En activité',false),
	(284, 'https://www.motoplanete.com/Nash/Nash-motorcycle-compagny-logo.gif', 'Nash', 'Etats-Unis', '2002', 'En activité',false),
	(285, 'https://www.motoplanete.com/ncr/NCR.jpg', 'NCR', 'Italie', '1967', 'En activité',false),
	(286, 'https://www.motoplanete.com/Neander-allemagne-kiel/Neander-logo.png', 'Neander (ALL - Kiel)', 'Allemagne', '2005', 'En activité',false),
	(287, 'https://www.motoplanete.com/neuwai/neuwai-logo.png', 'NeuWai', 'Corée', '2019', 'En activité',false),
	(288, 'https://www.motoplanete.com/Newron-Motors/Newron-Motors-logo.png', 'Newron Motors', 'France', '2016', 'En activité',false),
	(289, 'https://www.motoplanete.com/Nipponia/Nipponia-logo.jpg', 'Nipponia', 'Grèce', '1992', 'En activité',false),
	(290, 'https://www.motoplanete.com/NIU/NIU-logo.png', 'NIU', 'Chine', '2015', 'En activité',false),
	(291, 'https://www.motoplanete.com/norton/NortonLogo.gif', 'Norton', 'Angleterre', '1898', 'En activité',false),
	(292, 'https://www.motoplanete.com/Nova-Motors/Nova-motors-logo.gif', 'Nova Motors', 'Allemagne', '2010', 'En activité',false),
	(293, 'https://www.motoplanete.com/novus-motorcycle/Novus-logo.gif', 'Novus', 'Allemagne', '2009', 'En activité',false),
	(294, 'https://www.motoplanete.com/NXT-Motors/NXT-motors-logo2.jpg', 'NXT Motors', 'Pays-Bas', '2015', 'En activité',false),
	(295, 'https://www.motoplanete.com/OCC-Orange-County-Choppers/OCC-orangecountychoppers.png', 'O.C.C - Orange County Choppers', 'Etats-Unis', '1999', 'En activité',false),
	(296, 'https://www.motoplanete.com/omc-japon/omc-japon-logo.png', 'OMC - Orange Boulevard Motorcycle', 'Japon', '2014', 'En activité',false),
	(297, 'https://www.motoplanete.com/Orcal/Orcal-logo.jpg', 'Orcal', 'France', '2013', 'En activité',false),
	(298, 'https://www.motoplanete.com/Oset/Oset-logo.png', 'Oset', 'Angleterre', '2004', 'En activité',false),
	(299, 'https://www.motoplanete.com/Over/over-logo.png', 'Over', 'Japon', '1988', 'En activité',false),
	(300, 'https://www.motoplanete.com/Overbikes/Overbikes-logo.jpg', 'Overbikes', 'Italie', '2002', 'En activité',false),
	(301, 'https://www.motoplanete.com/Pagsta/Pagsta-logo.png', 'Pagsta', 'Etats-Unis', '1984', 'En activité',false),
	(302, 'https://www.motoplanete.com/Palmo/Palmo.jpg', 'Palmo', 'Allemagne', '2008', 'En activité',false),
	(303, 'https://www.motoplanete.com/Panthera/Panthera-logo.jpg', 'Pantera', 'Chine', '2010', 'En activité',false),
	(304, 'https://www.motoplanete.com/Pantera-Custom-Motorcycles/Pantera-Custom-motorcycle-logo.gif', 'Pantera Custom Motorcycles', 'Etats-Unis', '2004', 'En activité',false),
	(305, 'https://www.motoplanete.com/Paton/Paton-logo-mini-2.jpg', 'Paton', 'Italie', '1958', 'En activité',false),
	(306, 'https://www.motoplanete.com/Peda-motor/PEDA-Motor-logo.jpg', 'Peda Motor', 'Italie', '2004', 'En activité',false),
	(307, 'https://www.motoplanete.com/Peraves/Peraves-logo.png', 'Peraves', 'Suisse', '1974', 'En activité',false),
	(308, 'https://www.motoplanete.com/Peregrine/Peregrine-logo.jpg', 'Peregrine', 'Angleterre', '2011', 'En activité',false),
	(309, 'https://www.motoplanete.com/Peugeot/Peugeot-logo.jpg', 'Peugeot', 'France', '1899', 'En activité',false),
	(310, 'https://www.motoplanete.com/PGO/PGO-logo.jpg', 'PGO', 'Taïwan', '1964', 'En activité',false),
	(311, 'https://www.motoplanete.com/Pierobon/Pierobon-logo.jpg', 'Pierobon', 'Italie', '1963', 'En activité',false),
	(312, 'https://www.motoplanete.com/Pioneer/Pioneer-chine-logo.jpg', 'Pioneer', 'Chine', '2002', 'En activité',false),
	(313, 'https://www.motoplanete.com/Polini/Polini_logo.svg.png', 'Polini', 'Italie', '1945', 'En activité',false),
	(314, 'https://www.motoplanete.com/Pony-suisse/pony-moto-suisse-logo.jpg', 'Pony (SWISS)', 'Suisse', '1961', 'En activité',false),
	(315, 'https://www.motoplanete.com/Pow-Wow-Moto/PowWowMoto-logo.jpg', 'Pow Wow Moto', 'Canada', '0', 'En activité',false),
	(316, 'https://www.motoplanete.com/Precision-Cycle-Works/precision-cycle-work-logo.jpg', 'Precision Cycle Works', 'Etats-Unis', '2001', 'En activité',false),
	(317, 'https://www.motoplanete.com/Puma-uk/puma-engineering-logo.png', 'Puma ( UK)', 'Angleterre', '0', 'En activité',false),
	(318, 'https://www.motoplanete.com/Regal-Raptor/Regal-Raptor-logo.png', 'Regal Raptor', 'Chine', '1990', 'En activité',false),
	(319, 'https://www.motoplanete.com/Regent-suede/Logo_Regent_motorcycles.gif', 'Regent (SWE)', 'Suède', '2018', 'En activité',false),
	(320, 'https://www.motoplanete.com/rieju/rieju.gif', 'Rieju', 'Espagne', '1934', 'En activité',false),
	(321, 'https://www.motoplanete.com/RMK/RMK-logo.png', 'RMK', 'Finlande', '2018', 'En activité',false),
	(322, 'https://www.motoplanete.com/Rotobox/Rotobox-logo.png', 'Rotobox', 'Slovénie', '2005', 'En activité',false),
	(323, 'https://www.motoplanete.com/royal-enfield/royal-enfield-logo.gif', 'Royal-Enfield', 'Inde', '1901', 'En activité',false),
	(324, 'https://www.motoplanete.com/RPS/RPS-logo.jpg', 'RPS', 'France', '2011', 'En activité',false),
	(325, 'https://www.motoplanete.com/sachs/sachs-logo.jpg', 'Sachs', 'Allemagne', '1894', 'En activité',false),
	(326, 'https://www.motoplanete.com/Sandi%20/Sandi-logo.png', 'Sandi', 'Chine', '1989', 'En activité',false),
	(327, 'https://www.motoplanete.com/Sanli/Sanli-logo.jpg', 'Sanli', 'Chine', '1983', 'En activité',false),
	(328, 'https://www.motoplanete.com/Sanya/Sanya-logo.jpg', 'Sanya', 'Chine', '1998', 'En activité',false),
	(329, 'https://www.motoplanete.com/Sarolea/Sarolea.png', 'Sarolea', 'Belgique', '1850', 'En activité',false),
	(330, 'https://www.motoplanete.com/savic-motrocycle/Savic-logo.jpg', 'Savic', 'Australie', '2015', 'En activité',false),
	(331, 'https://www.motoplanete.com/saxon/saxon-logo.jpg', 'Saxon', 'Etats-Unis', '2004', 'En activité',false),
	(332, 'https://www.motoplanete.com/Schwinn/Schwinn-logo.jpg', 'Schwinn', 'Etats-Unis', '2005', 'En activité',false),
	(333, 'https://www.motoplanete.com/Scomadi/Scomadi-logo.jpg', 'Scomadi', 'Angleterre', '2005', 'En activité',false),
	(334, 'https://www.motoplanete.com/Scoot-E/Scoot-E-logo-ombre.jpg', 'Scoot-E', 'Etats-Unis', '0', 'En activité',false),
	(335, 'https://www.motoplanete.com/Scorpa/scorpa_logo.jpg', 'Scorpa', 'France', '1993', 'En activité',false),
	(336, 'https://www.motoplanete.com/SEAT/SEAT-logo.png', 'SEAT', 'Espagne', '1950', 'En activité',false),
	(337, 'https://www.motoplanete.com/Segway-Ninebot/segway-ninebot-logo.jpg', 'Segway-Ninebot', 'Chine', '2015', 'En activité',false),
	(338, 'https://www.motoplanete.com/Senke/senke-logo.jpg', 'Senke', 'Chine', '1996', 'En activité',false),
	(339, 'https://www.motoplanete.com/Shanyang/Shanyang-logo.jpg', 'Shanyang', 'Chine', '1987', 'En activité',false),
	(340, 'https://www.motoplanete.com/sherco/sherco-logo.gif', 'Sherco', 'France', '1998', 'En activité',false),
	(341, 'https://www.motoplanete.com/Shineray/Shineray-logo.jpg', 'Shineray', 'Chine', '1997', 'En activité',false),
	(342, 'https://www.motoplanete.com/Sinnis/Sinnis-logo.png', 'Sinnis', 'Angleterre', '2006', 'En activité',false),
	(343, 'https://www.motoplanete.com/Sinski/sinski-logo.jpg', 'Sinski', 'Chine', '1993', 'En activité',false),
	(344, 'https://www.motoplanete.com/Skygo/Skygo-logo.jpg', 'Skygo', 'Philippines', '2003', 'En activité',false),
	(345, 'https://www.motoplanete.com/SkyTeam/Skyteam-logo.gif', 'SkyTeam', 'Chine', '1999', 'En activité',false),
	(346, 'https://www.motoplanete.com/Solex/Solex-logo.jpg', 'Solex', 'France', '1905', 'En activité',false),
	(347, 'https://www.motoplanete.com/Spigaou/Spigaou-logo.jpg', 'Spigaou', 'France', '2007', 'En activité',false),
	(348, 'https://www.motoplanete.com/Srivaru-Motors/Srivaru-Motors-logo-hd.png', 'Srivaru Motors', 'Inde', '2018', 'En activité',false),
	(349, 'https://www.motoplanete.com/Steed/steed-logo.gif', 'Steed', 'Etats-Unis', '1994', 'En activité',false),
	(350, 'https://www.motoplanete.com/Stonegate/stonegate-logo.png', 'Stonegate', 'Australie', '2010', 'En activité',false),
	(351, 'https://www.motoplanete.com/Sukida/Sukida-logo.jpg', 'Sukida', 'Chine', '2001', 'En activité',false),
	(352, 'https://www.motoplanete.com/Sumco/Sumco-logo.jpg', 'Sumco', 'Espagne', '0', 'En activité',false),
	(353, 'https://www.motoplanete.com/Hainan-Sundiro/Hainan-Sundiro-logo.jpg', 'Sundiro', 'Chine', '1988', 'En activité',false),
	(354, 'https://www.motoplanete.com/Super-Soco/Super-Soco-logo.jpg', 'Super Soco', 'Autriche', '2016', 'En activité',false),
	(355, 'https://www.motoplanete.com/Sur-ron/Sur-ron-logo.png', 'Sur-Ron', 'Chine', '2014', 'En activité',false),
	(356, 'https://www.motoplanete.com/suzuki/Suzuki.png', 'Suzuki', 'Japon', '1909', 'En activité',false),
	(357, 'https://www.motoplanete.com/SWM/SWM-Logo.png', 'SWM', 'Italie', '1971', 'En activité',false),
	(358, 'https://www.motoplanete.com/SXT-Scooters/logo-sxt-scooter.jpg', 'SXT Scooters', 'France', '2006', 'En activité',false),
	(359, 'https://www.motoplanete.com/Sym/SYM-logo.jpg', 'Sym', 'Taïwan', '1954', 'En activité',false),
	(360, 'https://www.motoplanete.com/Tacita/Tacita-logo-petit.jpg', 'Tacita', 'Italie', '2009', 'En activité',false),
	(361, 'https://www.motoplanete.com/Tak-Taz/Tak-taz-motor-logo.png', 'Tak Taz', 'Iran', '1997', 'En activité',false),
	(362, 'https://www.motoplanete.com/Tank-sports/Tank-sports-logo.jpg', 'Tank Sports', 'Etats-Unis', '2001', 'En activité',false),
	(363, 'https://www.motoplanete.com/tao-motor/Tao-motor-logo-2.jpg', 'Tao Motor', 'Chine', '0', 'En activité',false),
	(364, 'https://www.motoplanete.com/tao-tao/taotao-logo.png', 'Taotao', 'Etats-Unis', '0', 'En activité',false),
	(365, 'https://www.motoplanete.com/Tarform-Motorcycles/tarform-logo.jpg', 'Tarform Motorcycles', 'Etats-Unis', '2018', 'En activité',false),
	(366, 'https://www.motoplanete.com/Taro/taro.gif', 'Taro', 'Chine', '2001', 'En activité',false),
	(367, 'https://www.motoplanete.com/Tarso-Marques-Concept/Tarso-Marques-logo-mini.gif', 'Tarso Marques Concept', 'Brésil', '1999', 'En activité',false),
	(368, 'https://www.motoplanete.com/Tauris/tauris-logo.png', 'Tauris', 'Allemagne', '2005', 'En activité',false),
	(369, 'https://www.motoplanete.com/Tayo/Tayo-logo.gif', 'Tayo', 'Chine', '2003', 'En activité',false),
	(370, 'https://www.motoplanete.com/Tempus/Tempus-logo-big.png', 'Tempus', 'Canada', '2016', 'En activité',false),
	(371, 'https://www.motoplanete.com/Terra-Modena/Terra-Modena-logo.jpg', 'Terra Modena', 'Italie', '2004', 'En activité',false),
	(372, 'https://www.motoplanete.com/TGB-Taiwan-Golden-Bee/TGB-logo-big.png', 'TGB - Taiwan Golden Bee', 'Taïwan', '1965', 'En activité',false),
	(373, 'https://www.motoplanete.com/Thompson-Choppers/thompson-choppers-logo.jpg', 'Thompson Choppers', 'Etats-Unis', '2010', 'En activité',false),
	(374, 'https://www.motoplanete.com/Thumpstar/thumpstar-logo.jpg', 'Thumpstar', 'Australie', '2004', 'En activité',false),
	(375, 'https://www.motoplanete.com/Tianma/Tianma_logo.png', 'TianMa', 'Chine', '1995', 'En activité',false),
	(376, 'https://www.motoplanete.com/Timeless/Timeless-logo.jpg', 'Timeless', 'Etats-Unis', '2007', 'En activité',false),
	(377, 'https://www.motoplanete.com/Titan-us/titan-logo.png', 'Titan (USA)', 'Etats-Unis', '1994', 'En activité',false),
	(378, 'https://www.motoplanete.com/TM/TM-racing-logo.jpg', 'TM', 'Italie', '1977', 'En activité',false),
	(379, 'https://www.motoplanete.com/TNT-MOTOR/tnt-motor-logo.jpg', 'TNT MOTOR', 'France', '0', 'En activité',false),
	(380, 'https://www.motoplanete.com/Tork-Motors/Tork-Motors-logo.jpg', 'Tork Motors', 'Inde', '2009', 'En activité',false),
	(381, 'https://www.motoplanete.com/Torrot/Torrot-logo.jpg', 'Torrot', 'Espagne', '1961', 'En activité',false),
	(382, 'https://www.motoplanete.com/Travertson/Travertson-logo.png', 'Travertson', 'Etats-Unis', '2008', 'En activité',false),
	(383, 'https://www.motoplanete.com/triumph/Triumph.png', 'Triumph', 'Angleterre', '1885', 'En activité',false),
	(384, 'https://www.motoplanete.com/TRS/TRS-logo.jpg', 'TRS', 'Espagne', '2013', 'En activité',false),
	(385, 'https://www.motoplanete.com/Tube-Investments/Tube-Investments-logo.png', 'Tube Investments', 'Inde', '1955', 'En activité',false),
	(386, 'https://www.motoplanete.com/Tucson-Roadson/roadson-logo-200.png', 'Tucson / Roadson', 'France', '1994', 'En activité',false),
	(387, 'https://www.motoplanete.com/Turbho/turbho-logo.jpg', 'Turbho', 'Pays-Bas', '2009', 'En activité',false),
	(388, 'https://www.motoplanete.com/TVS/TVS-Motor-Logo.jpg', 'TVS', 'Inde', '1978', 'En activité',false),
	(389, 'https://www.motoplanete.com/UBCO/ubco-logo.png', 'UBCO', 'Nouvelle-Zélande', '2014', 'En activité',false),
	(390, 'https://www.motoplanete.com/Ujet/Ujet-logo.png', 'Ujet', 'Luxembourg', '2015', 'En activité',false),
	(391, 'https://www.motoplanete.com/Ultraviolette/ultraviolette-logo.png', 'Ultraviolette', 'Inde', '2014', 'En activité',false),
	(392, 'https://www.motoplanete.com/ural/Ural-logo.gif', 'Ural', 'Russie', '1941', 'En activité',false),
	(393, 'https://www.motoplanete.com/Vahrenkamp/Vahrenkamp-logo-2.jpg', 'Vahrenkamp', 'Allemagne', '2008', 'En activité',false),
	(394, 'https://www.motoplanete.com/Vanguard/Vanguard-logo.gif', 'Vanguard', 'Etats-Unis', '2016', 'En activité',false),
	(395, 'https://www.motoplanete.com/Vastro/vastro-logo.png', 'Vastro', 'France', '2007', 'En activité',false),
	(396, 'https://www.motoplanete.com/Vectrix/Vectrix-logo.png', 'Vectrix', 'Etats-Unis', '1996', 'En activité',false),
	(397, 'https://www.motoplanete.com/Vee-Two/vee-two-australia-logo2.jpg', 'Vee Two', 'Australie', '1979', 'En activité',false),
	(398, 'https://www.motoplanete.com/Veitis/veitis-electric-motorcycle-logo.gif', 'Veitis', 'Angleterre', '2016', 'En activité',false),
	(399, 'https://www.motoplanete.com/Veli/Velimotor-logo.gif', 'Veli', 'Chine', '0', 'En activité',false),
	(400, 'https://www.motoplanete.com/Velorex/Velorex-logo.jpg', 'Velorex', 'Pérou', '2004', 'En activité',false),
	(401, 'https://www.motoplanete.com/Vepe/Vepe-france-logo.jpg', 'Vepe', 'France', '0', 'En activité',false),
	(402, 'https://www.motoplanete.com/vertemati/vertemati-logo.jpg', 'Vertemati', 'Italie', '1993', 'En activité',false),
	(403, 'https://www.motoplanete.com/Vertigo/Vertigo-logo.png', 'Vertigo', 'Espagne', '2012', 'En activité',false),
	(404, 'https://www.motoplanete.com/Vibgyor/Vibgyor-logo.gif', 'Vibgyor', 'Inde', '2009', 'En activité',false),
	(405, 'https://www.motoplanete.com/Vins-Motor/Vins-motor-logo-3.gif', 'Vins Motor', 'Italie', '2017', 'En activité',false),
	(406, 'https://www.motoplanete.com/Voge-china-motorcycle/Voge-Motorcycle-logo.jpg', 'Voge', 'Chine', '2019', 'En activité',false),
	(407, 'https://www.motoplanete.com/Vyrus/Vyrus-logo.jpg', 'Vyrus', 'Italie', '2003', 'En activité',false),
	(408, 'https://www.motoplanete.com/Wacco/waccoLogo.png', 'Wacco', 'Corée', '2012', 'En activité',false),
	(409, 'https://www.motoplanete.com/Walt-Siegl/Walt-Siegl-Motorcycles-logo.jpg', 'Walt Siegl Motorcycles', 'Etats-Unis', '2007', 'En activité',false),
	(410, 'https://www.motoplanete.com/Walton-Motors/Walton-motors-logo.jpg', 'Walton Motors', 'Bangladesh', '2008', 'En activité',false),
	(411, 'https://www.motoplanete.com/WattEver/WattEver-logo.jpg', 'WattEver', 'France', '2017', 'En activité',false),
	(412, 'https://www.motoplanete.com/Wild%20West/Wild-West-MC-logo.jpg', 'Wild West', 'Etats-Unis', '1995', 'En activité',false),
	(413, 'https://www.motoplanete.com/WK-Bikes/WK-Bikes-logo.png', 'WK Bikes', 'Angleterre', '0', 'En activité',false),
	(414, 'https://www.motoplanete.com/WT-Motors/WT-Motors-logo.png', 'WT Motors', 'Italie', '0', 'En activité',false),
	(415, 'https://www.motoplanete.com/Xinling/xinling-logo.jpg', 'Xinling', 'Chine', '1997', 'En activité',false),
	(416, 'https://www.motoplanete.com/yamaha/Yamaha.png', 'Yamaha', 'Japon', '1887', 'En activité',false),
	(417, 'https://www.motoplanete.com/YCR-Motor/YCR-Motor-2.jpg', 'YCR Motor', 'Chine', '0', 'En activité',false),
	(418, 'https://www.motoplanete.com/YinGang/yingang-logo.jpg', 'YinGang', 'Chine', '1996', 'En activité',false),
	(419, 'https://www.motoplanete.com/zapp-scooter/Zapp-logo.jpg', 'Zapp', 'Angleterre', '2017', 'En activité',false),
	(420, 'https://www.motoplanete.com/Zero-Engineering/Zero-Engineering-logo-1.png', 'Zero Engineering', 'Japon', '1992', 'En activité',false),
	(421, 'https://www.motoplanete.com/zero/zero-motorcycles-logo-2014.gif', 'Zero Motorcycles', 'Etats-Unis', '2006', 'En activité',false),
	(422, 'https://www.motoplanete.com/zongshen/zongshen-logo.gif', 'Zongshen', 'Chine', '1992', 'En activité',false),
	(423, 'https://www.motoplanete.com/Ztech/ZTech-bike-logo.png', 'ZTech', 'Hongrie', '2011', 'En activité',false),
	(424, 'https://www.motoplanete.com/Zvexx/Zvexx-logo.png', 'Zvexx', 'Suisse', '2016', 'En activité',false);




